export const forMetaData = {
  metadataBase: new URL('https://www.unitystory.info'),
  title: 'Unity Compendium',
  description:
    'Immerse yourself in a meticulously crafted fantasy world filled with rich lore, breathtaking landscapes, and unique creations. Explore a universe brought to life through detailed world-building, where imagination and creativity shape every corner.',
  keywords: [
    'fantasy',
    'world-building',
    'Unity Compendium',
    'lore',
    'legend',
    'legends',
    'myth',
    'myths',
    'culture',
    'unity',
    'ceremony',
    'ceremonies',
    'conflict',
    'conflicts',
    'deity',
    'deities',
    'god',
    'gods',
    'art',
    'imagination',
    'creation',
  ],
  authors: { name: 'Philip Rurka' },
  creator: 'Philip Rurka',
  publisher: 'Philip Rurka',
  openGraph: {
    images: {
      url: 'https://www.unitystory.info/unity-logo.png',
      width: 650,
      height: 650,
      type: 'image/png',
    },
    locale: 'en_US',
    type: 'article',
    url: 'https://www.unitystory.info',
    siteName: 'Unity Compendium',
    authors: ['Philip Rurka'],
  },
  icons: {
    icon: '/unity-logo.png',
  },
  verification: {
    google: 'google',
  },
  assets: [
    'https://fonts.googleapis.com/css2?family=Lexend:wght@300;500&display=swap',
    'https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&display=swap',
    '/layout-background.jpg',
    '/search-modal-background.jpg',
    '/unity-logo.png',
  ],
  category: 'Fantasy',
  alternates: {
    canonical: 'https://unitystory.info',
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      maxImagePreview: 'large',
    },
  },
  other: {
    sitemap: 'https://www.unitystory.info/sitemap.xml',
  },
};

export const forJsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'CreativeWorkSeries',
      name: 'Unity Compendium',
      description: 'Immerse yourself in a meticulously crafted fantasy world...',
      author: { '@type': 'Person', name: 'Philip Rurka' },
      creator: { '@type': 'Person', name: 'Philip Rurka' },
      publisher: { '@type': 'Person', name: 'Philip Rurka' },
      genre: 'Fantasy',
      keywords: ['fantasy', 'world-building', 'lore', 'Unity Compendium'],
      inLanguage: 'en-US',
      url: 'https://www.unitystory.info',
      image: 'https://www.unitystory.info/unity-logo.png',
      mainEntityOfPage: { '@type': 'WebPage', '@id': 'https://www.unitystory.info' },
    },
    {
      '@type': 'WebSite',
      url: 'https://www.unitystory.info',
      name: 'Unity Compendium',
    },
    {
      '@type': 'Organization',
      name: 'Unity Compendium',
      url: 'https://www.unitystory.info',
      logo: 'https://www.unitystory.info/unity-logo.png',
    },
  ],
};
