import clsx from 'clsx';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/Components/Header';
import getByContentModel from '@/Fetchers/contentful/getByContentModel';
import '@/Styles/globals.css';
import { HierarchyLayoutType } from '@/Types/contentful-codegen/SimplerContentfulTypes';

import HierarchyNav from '../src/HierarchyNav';
import HierarchyNavContextProvider from '../src/providers/contexts/HierarchyNavContextProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: RootLayoutProps) {
  const [hierarchyLayout] = (await getByContentModel('hierarchyLayout')) as HierarchyLayoutType[];

  return (
    <html lang="en">
      <body className={clsx('h-screen bg-slate-50', inter.className)}>
        <HierarchyNavContextProvider>
          <Header />
          <HierarchyNav hierarchyLayout={hierarchyLayout} />
          <div>{children}</div>
        </HierarchyNavContextProvider>
      </body>
    </html>
  );
}
