module.exports = {
  extends: [
    "next/core-web-vitals",
    "airbnb-base",
    "airbnb-typescript/base",
    "prettier",
    "plugin:react-hooks/recommended",
  ],
  rules: {
    "import/extensions": "off",
    "react/no-unescaped-entities": "off",
    "@next/next/no-page-custom-font": "off",
    "import/no-extraneous-dependencies": "off",
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
  },
  ignorePatterns: [
    "node_modules",
    ".next",
    "public",
    "postcss.config.cjs",
    "prettier.config.cjs",
    "migrate-mongo-config.js",
    "next.config.mjs",
    "mongodb/*",
    "migrations/*",
    "__mocks__/*",
    "@types/contentful-codegen/*",
    // ".eslintrc",
    // "*.config.[jt]s",
    // "node_modules",
    // ".next",
    // "public",
  ],
};
